### ISSUE TITLE
install script breaks

### ISSUE THREAD

**Issue by Damoness** [VISI-ONE/create-react-native-web-app#17]
npx create-react-native-web-app myApp
![image](https://user-images.githubusercontent.com/5622121/49365780-98d75e00-f722-11e8-9946-e04e1da85235.png)

**Comment by orYoffe** [comment]
@Damoness Hi,
A few details about your system would help, for example, is it windows, linux?
It might be a permission problem and you might want to run it with `sudo` like this:
`sudo npx create-react-native-web-app myApp`

if that doesn't work please try to install the package globally and then to run the command
like this:
`npm i -g create-react-native-web-app`
`create-react-native-web-app myApp`

Hope it helps :)

**Comment by Damoness** [comment]
> @Damoness Hi,
> A few details about your system would help, for example, is it windows, linux?
> It might be a permission problem and you might want to run it with `sudo` like this:
> `sudo npx create-react-native-web-app myApp`
> 
> if that doesn't work please try to install the package globally and then to run the command
> like this:
> `npm i -g create-react-native-web-app`
> `create-react-native-web-app myApp`
> 
> Hope it helps :)

My system is macOS 10.13.6

The same error
![image](https://user-images.githubusercontent.com/5622121/49696910-da1cb180-fbeb-11e8-99b5-ae627a459967.png)

**Comment by orYoffe** [comment]
Hi @haruelrovix & @Damoness ,

please check if you still have issues with the new version 0.1.8 :)

thanks for notifying me about the bug

**Comment by haruelrovix** [comment]
@orYoffe seems I still got the error 🤔

- Install `0.1.8`
```
➜  Projects npm i -g create-react-native-web-app@latest
/Users/haruelrovix/.nvm/versions/node/v10.13.0/bin/create-react-native-web-app -> /Users/haruelrovix/.nvm/versions/node/v10.13.0/lib/node_modules/create-react-native-web-app/cli.js
+ create-react-native-web-app@0.1.8
updated 1 package in 5.073s
```

- bootstrap a project
```
➜  Projects create-react-native-web-app g1tphone
      ⏳ Creating React Native Web App by the name of g1tphone ...

      ✅ Created project folder.

      ✅ Added project files.

      ⏳ Installing project dependencies...

yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:651
    throw err;
    ^

Error: Command failed: cd g1tphone && yarn
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (/Users/haruelrovix/.nvm/versions/node/v10.13.0/lib/node_modules/create-react-native-web-app/cli.js:79:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Comment by haruelrovix** [comment]
@orYoffe it's not an issue with CRNWA but yarn (?)

What I did:
1. Go to the project
    ```
    $ cd g1tphone
    ```
1. Remove `yarn.lock`
    ```
    $ rm yarn.lock
    ```
1. Run `yarn` again
    ```
    $ yarn
    ```

Result:
```
➜  g1tphone yarn
yarn install v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 73.71s.
```

🎉 

References:
- Error on install 404 on har-validator-5.1.2.tgz, [source](https://github.com/yarnpkg/yarn/issues/6702#issuecomment-442314783)
- Extracting the tar content of undefined failed, [here](https://github.com/yarnpkg/yarn/issues/6312#issuecomment-446102010)

**Comment by orYoffe** [comment]
@haruelrovix please try the new release v0.1.9 
https://github.com/VISI-ONE/create-react-native-web-app/releases/tag/0.1.9

**Comment by haruelrovix** [comment]
@orYoffe YOU. ARE. AWESOME!

```
➜  Projects npm i -g create-react-native-web-app@latest
/Users/haruelrovix/.nvm/versions/node/v10.13.0/bin/create-react-native-web-app -> /Users/haruelrovix/.nvm/versions/node/v10.13.0/lib/node_modules/create-react-native-web-app/cli.js
+ create-react-native-web-app@0.1.9
updated 1 package in 6.742s
```

```
➜  Projects create-react-native-web-app g1thub
      ⏳ Creating React Native Web App by the name of g1thub ...

      ✅ Created project folder.

      ✅ Added project files.

      ⏳ Installing project dependencies...

yarn install v1.12.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 122.75s.
      ✅ Installed project dependencies.

      ✅ Done! 😁👍 Your project is ready for development.


        * change directory to your new project
        $ cd g1thub

        $ Then run the these commands to get started:

        * To run development Web server
        $ yarn web

        * To run Android on connected device (after installing Android Debug Bridge "adb" - https://developer.android.com/studio/releases/platform-tools)
        $ yarn android

        * To run ios simulator (after installing Xcode - only on Apple devices)
        $ yarn ios

        * To run tests for Native and Web
        $ yarn test

        * To run build for Web
        $ yarn build
```

👏
