### ISSUE TITLE
Project won't start

### ISSUE THREAD

**Issue by rborn** [VISI-ONE/create-react-native-web-app#19]
**Describe the bug**
Trying to run the script to create a project, it won't finish due to an yarn error
Any idea?

🤗

**To Reproduce**
1. $ create-react-native-web-app rnw
2. 💥

**Expected behavior**
It should finish the installation :)

**Additional context**
- OsX High Sierra
- yarn 1.7.0
- node v10.9.0

**Output**
~~~
$ create-react-native-web-app rnw
      ⏳ Creating React Native Web App by the name of rnw ...

      ✅ Created project folder.

      ✅ Added project files.

      ⏳ Installing project dependencies...

yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Work/tmp/rnw/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:640
    throw err;
    ^


Error: Command failed: cd rnw && yarn
    at checkExecSyncError (child_process.js:600:11)
    at execSync (child_process.js:637:13)
    at Object.<anonymous> (/Users/Dan/.npm-global/lib/node_modules/create-react-native-web-app/cli.js:79:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
~~~

**Comment by orYoffe** [comment]
hi @rborn ,

it seems like the `yarn` command to install the dependencies failed on the way.
you might want to try to use the cli with `sudo` for permission like this:
```
$ sudo create-react-native-web-app rnw
```

I saw this once, I hope it solves it. I'm not sure myself why it does that. :)

**Comment by rborn** [comment]
using `sudo` is not ok

**Comment by orYoffe** [comment]
Hi @rborn ,

Do you mean that `sudo` doesn't work for you and the problem might be something else?

**Comment by rborn** [comment]
@orYoffe I didn't test yet, I'll try a little later
