### ISSUE TITLE
Error: Command failed when Installing project dependencies (v0.1.7)

### ISSUE THREAD

**Issue by haruelrovix** [VISI-ONE/create-react-native-web-app#20]
**Describe the bug**
Couldn't initialise the project successfully.

**To Reproduce**
1. Install `latest` version
```
$ npm i -g create-react-native-web-app@0.1.7
```
2. Initialise a project
```
$ create-react-native-web-app gitphone2
```
3. Got an error
```
      ⏳ Installing project dependencies...

yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:651
    throw err;
    ^

Error: Command failed: cd gitphone2 && yarn
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Object.<anonymous> (/Users/haruelrovix/.nvm/versions/node/v10.13.0/lib/node_modules/create-react-native-web-app/cli.js:79:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Expected behavior**
CRNWA project created successfully. Tried **v0.1.6** and it worked!

1. Install v0.1.6
```
$ npm i -g create-react-native-web-app@0.1.6
```
2. Initialise a project
```
➜  Projects create-react-native-web-app gitphone
      ⏳ Creating React Native Web App by the name of gitphone ...

      ✅ Created project folder.

      ✅ Added project files.

      ⏳ Installing project dependencies...

yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 42.80s.
      ✅ Installed project dependencies.

      ✅ Done! 😁👍 Your project is ready for development.


        * change directory to your new project
        $ cd gitphone

        $ Then run the these commands to get started:

        * To run development Web server
        $ yarn web

        * To run Android on connected device (after installing Android Debug Bridge "adb" - https://developer.android.com/studio/releases/platform-tools)
        $ yarn android

        * To run ios simulator (after installing Xcode - only on Apple devices)
        $ yarn ios

        * To run tests for Native and Web
        $ yarn test

        * To run build for Web
        $ yarn build
```

|**Additional**|**context**|
|-|-|
|`nvm list`|v10.13.0|
|`npm -v`|6.4.1|

**Comment by orYoffe** [comment]
duplicate #17
